### ISSUE TITLE
Import mixin fails with no such file found error

### ISSUE THREAD

**Issue by millisami** [ajile/ember-cli-geolocation#8]
I installed the addon and setup in index controller as per Readme.
But now when I start the server, it errors out with no mixin file found!!

```
File: cabbyguide/controllers/index.js
ENOENT, no such file or directory '/Users/millisami/Emberapps/cabbyguide/tmp/tree_merger-tmp_dest_dir-ZzBUyjI5.tmp/ember-cli-geolocation/mixins/geolocation-mixin.js'
Error: ENOENT, no such file or directory '/Users/millisami/Emberapps/cabbyguide/tmp/tree_merger-tmp_dest_dir-ZzBUyjI5.tmp/ember-cli-geolocation/mixins/geolocation-mixin.js'
    at Object.fs.statSync (fs.js:684:18)
    at addModule (/Users/millisami/Emberapps/cabbyguide/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:84:46)
    at addModule (/Users/millisami/Emberapps/cabbyguide/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:133:9)
    at /Users/millisami/Emberapps/cabbyguide/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:59:7
    at $$$internal$$tryCatch (/Users/millisami/Emberapps/cabbyguide/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
    at $$$internal$$invokeCallback (/Users/millisami/Emberapps/cabbyguide/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
    at $$$internal$$publish (/Users/millisami/Emberapps/cabbyguide/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:453:11)
    at $$rsvp$asap$$flush (/Users/millisami/Emberapps/cabbyguide/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1531:9)
    at process._tickCallback (node.js:419:13)
```
My system info:

```
$ ember -v
version: 0.1.2
node: 0.10.28
npm: 2.1.3
```

**Comment by ajile** [comment]
@millisami, sorry for a long response.

You should import mixin like that:

``` javascript
import GeoLocationMixin from 'cabbyguide/mixins/geolocation-mixin';
```

Replace `ember-cli-geolocation` by `cabbyguide` - because geolocation addon becames a part of your project.

PS: Thank you for this issue - I fixed up README file.
